project_id = "fxnpnmvvyktljkmukkei"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.get-invoice-pdf]
verify_jwt = false