// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxnpnmvvyktljkmukkei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bnBubXZ2eWt0bGprbXVra2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODE2OTcsImV4cCI6MjA2ODY1NzY5N30.I7XZsRAzFz0BSqUR5RaCP2xoCiKYb-d1vTcLzzB8VAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});